version: '2.1'
services:
  run-server:
    image: watch-hands
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - start
    volumes:
      - .:/watch-hands
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: {}
